org: jshong0907
#app: fast-api
service: fast-api

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-2

  ecr:
    images:
      fast_api_image:
        path: ./

package:
  individually: true

functions:
  ApiFunction:
    image:
      name: fast_api_image
    events:
      - http: ANY /
      - http: ANY /{proxy+}
